// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVhsG4roY2Apaj8Oh_KT6xyQyiMRWWeV8',
    appId: '1:953815861513:android:a46d44a382e4d0995e2bd8',
    messagingSenderId: '953815861513',
    projectId: 'denizli-ulku-ocaklari',
    storageBucket: 'denizli-ulku-ocaklari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYnpOVl2mDded_wSOY5h59TFJKyT5FTLc',
    appId: '1:953815861513:ios:7d5cdbfda16f15d75e2bd8',
    messagingSenderId: '953815861513',
    projectId: 'denizli-ulku-ocaklari',
    storageBucket: 'denizli-ulku-ocaklari.appspot.com',
    iosClientId: '953815861513-blvlh381sv0pld5mkpqjo1kvslsuom8m.apps.googleusercontent.com',
    iosBundleId: 'com.denizli.ulku.ocaklari.deriapp',
  );
}
